services:
  - type: web
    name: first-node-app
    runtime: node
    rootDir: first_node_app
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: bd0bexgjuwz55o2u7mkn-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: "true"